// src/router/routes.ts
// Centraliza las rutas de la app para evitar magic strings

export enum AppRoute {
  LOGIN = '/login',
  AUTH_REDIRECT = '/auth-redirect',
  HOME = '/',
  REDIRECT = '/redirect',
  REDIRECT_PATH = '/redirect/:path(.*)',
  ERROR_404 = '/404',
  ERROR_401 = '/401',
  DASHBOARD = '/dashboard',
  DOCUMENTATION = '/documentation',
  GUIDE = '/guide',
  PROFILE = '/profile',
  PERMISSION = '/permission',
  ICON = '/icon',
  COMPONENTS = '/components',
  CHARTS = '/charts',
  NESTED = '/nested',
  TABLE = '/table',
  EXAMPLE = '/example',
  TAB = '/tab',
  ERROR = '/error',
  ERROR_LOG = '/error-log',
  EXCEL = '/excel',
  ZIP = '/zip',
  PDF = '/pdf',
  PDF_DOWNLOAD = '/pdf/download',
  THEME = '/theme',
  CLIPBOARD = '/clipboard',
  EXTERNAL_LINK = '/external-link',
  MYDEMO = '/mydemo',
  DATABASE = '/database',
  // Components Demo Routes
  TINYMCE = '/components/tinymce',
  AVATAR_UPLOAD = '/components/avatar-upload',
  DROPZONE = '/components/dropzone',
  STICKY = '/components/sticky',
  COUNT_TO = '/components/count-to',
  MIXIN = '/components/mixin',
  BACK_TO_TOP = '/components/back-to-top',
  DRAG_DIALOG = '/components/drag-dialog',
  DRAG_SELECT = '/components/drag-select',
  // Charts Demo Routes
  KEYBOARD_CHART = '/charts/keyboard',
  LINE_CHART = '/charts/line',
  MIX_CHART = '/charts/mix-chart',
  // Nested Menu Routes
  NESTED_MENU1 = '/nested/menu1',
  NESTED_MENU1_1 = '/nested/menu1/menu1-1',
  NESTED_MENU1_2 = '/nested/menu1/menu1-2',
  NESTED_MENU1_2_1 = '/nested/menu1/menu1-2/menu1-2-1',
  NESTED_MENU1_2_2 = '/nested/menu1/menu1-2/menu1-2-2',
  NESTED_MENU1_3 = '/nested/menu1/menu1-3',
  NESTED_MENU2 = '/nested/menu2',
  // Table Demo Routes
  DYNAMIC_TABLE = '/table/dynamic-table',
  DRAG_TABLE = '/table/drag-table',
  INLINE_EDIT_TABLE = '/table/inline-edit-table',
  COMPLEX_TABLE = '/table/complex-table',
}

export const loginRedirectPath = (redirect: string) => `${AppRoute.LOGIN}?redirect=${redirect}`
