// Define unique view identifiers for permission mapping
export enum ViewId {
  REDIRECT = 'REDIRECT_VIEW',
  LOGIN = 'LOGIN_VIEW',
  AUTH_REDIRECT = 'AUTH_REDIRECT_VIEW',
  ERROR_404 = 'ERROR_404_VIEW',
  ERROR_401 = 'ERROR_401_VIEW',
  DASHBOARD = 'DASHBOARD_VIEW',
  DASHBOARD_ROOT = 'DASHBOARD_ROOT',
  DATABASE = 'DATABASE_VIEW',
  DATABASE_ROOT = 'DATABASE_ROOT',
  GUIDE = 'GUIDE_VIEW',
  GUIDE_ROOT = 'GUIDE_ROOT',
  PROFILE = 'PROFILE_VIEW',
  PROFILE_ROOT = 'PROFILE_ROOT',

  PERMISSION_ROOT = 'PERMISSION_ROOT',
  PERMISSION_PAGE = 'PERMISSION_PAGE',
  PERMISSION_DIRECTIVE = 'PERMISSION_DIRECTIVE',
  PERMISSION_ROLE = 'PERMISSION_ROLE',

  ICONS = 'ICONS_VIEW',
  ICONS_ROOT = 'ICONS_ROOT',

  EXAMPLE_ROOT = 'EXAMPLE_ROOT',
  EXAMPLE_CREATE_ARTICLE = 'EXAMPLE_CREATE_ARTICLE',
  EXAMPLE_EDIT_ARTICLE = 'EXAMPLE_EDIT_ARTICLE',
  EXAMPLE_LIST_ARTICLE = 'EXAMPLE_LIST_ARTICLE',

  TAB = 'TAB_VIEW',
  TAB_ROOT = 'TAB_ROOT',

  ERRORPAGES_ROOT = 'ERRORPAGES_ROOT',
  ERRORPAGES_401 = 'ERRORPAGES_401',
  ERRORPAGES_404 = 'ERRORPAGES_404',

  ERRORLOG = 'ERRORLOG_VIEW',
  ERRORLOG_ROOT = 'ERRORLOG_ROOT',

  EXCEL_ROOT = 'EXCEL_ROOT',
  EXCEL_EXPORT_EXCEL = 'EXCEL_EXPORT_EXCEL',
  EXCEL_EXPORT_SELECTED = 'EXCEL_EXPORT_SELECTED',
  EXCEL_EXPORT_MERGE_HEADER = 'EXCEL_EXPORT_MERGE_HEADER',
  EXCEL_UPLOAD_EXCEL = 'EXCEL_UPLOAD_EXCEL',

  ZIP_ROOT = 'ZIP_ROOT',
  ZIP_DOWNLOAD = 'ZIP_DOWNLOAD',

  PDF_ROOT = 'PDF_ROOT',
  PDF_VIEW = 'PDF_VIEW',
  PDF_DOWNLOAD = 'PDF_DOWNLOAD_VIEW',

  THEME = 'THEME_VIEW',
  THEME_ROOT = 'THEME_ROOT',
  CLIPBOARD = 'CLIPBOARD_VIEW',
  CLIPBOARD_ROOT = 'CLIPBOARD_ROOT',
  EXTERNAL_LINK = 'EXTERNAL_LINK_VIEW',
  EXTERNAL_LINK_ROOT = 'EXTERNAL_LINK_ROOT',

  MYDEMO_ROOT = 'MYDEMO_ROOT',
  MYDEMO_ELEMENT_DEMO = 'MYDEMO_ELEMENT_DEMO',
  MYDEMO_STORE_DEMO = 'MYDEMO_STORE_DEMO',
  // Component demo group
  COMPONENTS_ROOT = 'COMPONENTS_ROOT',
  // Component demo views
  TINYMCE_VIEW = 'TINYMCE_VIEW',
  AVATAR_UPLOAD_VIEW = 'AVATAR_UPLOAD_VIEW',
  DROPZONE_VIEW = 'DROPZONE_VIEW',
  STICKY_VIEW = 'STICKY_VIEW',
  COUNT_TO_VIEW = 'COUNT_TO_VIEW',
  MIXIN_VIEW = 'MIXIN_VIEW',
  BACK_TO_TOP_VIEW = 'BACK_TO_TOP_VIEW',
  DRAG_DIALOG_VIEW = 'DRAG_DIALOG_VIEW',
  DRAG_SELECT_VIEW = 'DRAG_SELECT_VIEW',
  // Charts demo group
  CHARTS_ROOT = 'CHARTS_ROOT',
  KEYBOARD_CHART_VIEW = 'KEYBOARD_CHART_VIEW',
  LINE_CHART_VIEW = 'LINE_CHART_VIEW',
  MIX_CHART_VIEW = 'MIX_CHART_VIEW',
  // Nested menu demo group
  NESTED_ROOT = 'NESTED_ROOT',
  MENU1_VIEW = 'MENU1_VIEW',
  MENU1_1_VIEW = 'MENU1_1_VIEW',
  MENU1_2_VIEW = 'MENU1_2_VIEW',
  MENU1_2_1_VIEW = 'MENU1_2_1_VIEW',
  MENU1_2_2_VIEW = 'MENU1_2_2_VIEW',
  MENU1_3_VIEW = 'MENU1_3_VIEW',
  MENU2_VIEW = 'MENU2_VIEW',
  // Table demo group
  TABLE_ROOT = 'TABLE_ROOT',
  DYNAMIC_TABLE_VIEW = 'DYNAMIC_TABLE_VIEW',
  DRAG_TABLE_VIEW = 'DRAG_TABLE_VIEW',
  INLINE_EDIT_TABLE_VIEW = 'INLINE_EDIT_TABLE_VIEW',
  COMPLEX_TABLE_VIEW = 'COMPLEX_TABLE_VIEW',
}
